### ISSUE TITLE
OMG THIS IS AWSOME!

### ISSUE THREAD

**Issue by snaildos** [FoxValleyMC/TelegramUI#1]
Dude! I'v been harrasing people to create a plugin like this, AND ITS DONE!!! I really want you to add a message when you join the server saying Welcome to the server, You have [AMOUNT OF UNREAD MAIL] type the command to read it all.

Please add that. Tysm!!!

**Comment by Atm85** [comment]
Good suggestion, I'll do it!

**Comment by snaildos** [comment]
Tysm, tell me when u done :D
