### ISSUE TITLE
Suggestion : Can you add multi language supoort?

### ISSUE THREAD

**Issue by GoodLucky777** [FoxValleyMC/TelegramUI#2]
I love this plugin so much!
 Can you add features that support multiple language translations? For example, can you create something like language.yml in your plugins folder so that translations are also supported? I would really appreciate it!

**Comment by Atm85** [comment]
Sure, any particular language or translation on your mind?

**Comment by GoodLucky777** [comment]
Yes, I can translate to Korean.
