### ISSUE TITLE
respons my request!

### ISSUE THREAD

**Issue by OwnerSCIFahrul** [FoxValleyMC/TelegramUI#3]
hello, thank you it plugin, and I edited this plugin code you, I need AliasPro.jar required this plugin code, which is softdepended, give me..

**Comment by Atm85** [comment]
AliasPro is not required to run, it just serves as a database to search players names when sending Telegrams.

 - [AliasPro-1.0.0.zip](https://github.com/TimelessMC/TelegramUI/files/4114149/AliasPro-1.0.0.zip)
